version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/Workflow.Pn/Workflow.Pn"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/Workflow.Pn/Workflow.Pn.Test"
  schedule:
    interval: daily